function history = run_curated_smoke()
%RUN_CURATED_SMOKE Execute one short GPU data-flow check for all scenarios.
settings = struct( ...
    "iterations", 1, ...
    "selfPlayGamesPerIteration", 9, ...
    "mctsSimulations", 1, ...
    "maxPlies", 2, ...
    "trainingStepsPerIteration", 1, ...
    "batchSize", 1, ...
    "evaluationGamesPerPosition", 1, ...
    "modelDirectory", "models/smoke", ...
    "replayDirectory", "replay/smoke");
history = train_endgame_alphazero(settings);
end
