function settings = config()
%CONFIG Return deterministic parameters for the endgame validation experiment.
settings = struct( ...
    "randomSeed", 20260727, ...
    "useGPU", true, ...
    "mctsSimulations", 32, ...
    "selfPlayGamesPerIteration", 16, ...
    "iterations", 10, ...
    "maxPlies", 120, ...
    "temperaturePlies", 10, ...
    "selfPlayTemperature", 1.0, ...
    "replayCapacity", 2000, ...
    "batchSize", 32, ...
    "trainingStepsPerIteration", 20, ...
    "learningRate", 1e-3, ...
    "puctConstant", 1.5, ...
    "promotionScore", 0.55, ...
    "scenarioPromotionThresholds", struct("default", 0.55), ...
    "evaluationGamesPerPosition", 2, ...
    "modelDirectory", "models", ...
    "replayDirectory", "replay");
end
