function settings = fullgame_config()
%FULLGAME_CONFIG Return parameters for resumable standard-opening training.
settings = struct( ...
    "randomSeed", 20260727, ...
    "useGPU", true, ...
    "networkFilters", 64, ...
    "residualBlocks", 3, ...
    "featureWidth", 512, ...
    "networkVersion", alphazero.fullgame_network_version(), ...
    "mctsSimulations", 32, ...
    "selfPlayGamesPerIteration", 8, ...
    "iterations", 1, ...
    "maxPlies", 300, ...
    "drawValue", -0.1, ...
    "temperaturePlies", 20, ...
    "selfPlayTemperature", 1.0, ...
    "replayCapacity", 10000, ...
    "batchSize", 64, ...
    "trainingStepsPerIteration", 40, ...
    "learningRate", 5e-4, ...
    "puctConstant", 1.5, ...
    "promotionScore", 0.5, ...
    "scenarioPromotionThresholds", struct("default", 0.5), ...
    "evaluationGamesPerPosition", 1, ...
    "modelDirectory", "models", ...
    "replayDirectory", fullfile("replay", "fullgame"), ...
    "logDirectory", fullfile("logs", "fullgame"));
end
